package consulairejedi

import (
	fight "Game/Jeux/GamePlay/Fight"
	save "Game/Jeux/Sauvegarde"
	"fmt"
	"os"
	"os/exec"
	"runtime"
	"strconv"
	"time"
)

const (
	Reset   = "\033[0m"
	Red     = "\033[91m"
	Green   = "\033[32m"
	Yellow  = "\033[93m"
	Blue    = "\033[34m"
	Magenta = "\033[35m"
	Cyan    = "\033[96m"
	White   = "\033[37m"
	gray    = "\033[90m"
)

var ClasseConsulaire1 save.Classe = save.Classe{"Guardian", 110, []save.Abilite{save.Abilite{"Meditation", 10, 0, 30, 1, 0, 0, "An Abilite for rest a litle bit during a fight.", 0, 0}, save.Abilite{"Force wave", 30, 25, 0, 1, 0, 0, "A projection of the force who atack the ennemie", 0, 0}}}
var ClasseConsulaire2 save.Classe = save.Classe{"Sentinel", 100, []save.Abilite{save.Abilite{"Toxic gaz", 40, 15, 0, 1, 0, 0, "A toxic Gaz for the enemie but not for you", 5, 15}, save.Abilite{"right hook", 40, 40, 0, 1, 0, 0, "A right hook on the face of the ennemie", 0, 0}}}
var ClasseConsulaire3 save.Classe = save.Classe{"Nurse", 120, []save.Abilite{save.Abilite{"Heal", 20, 0, 20, 1, 0, 0, "Heal yourself", 0, 0}, save.Abilite{"Toxic gaz", 40, 15, 0, 1, 0, 0, "A toxic Gaz for the enemie but not for you", 5, 15}}}

var ClasseConsulaireList [3]save.Classe = [3]save.Classe{ClasseConsulaire1, ClasseConsulaire2, ClasseConsulaire3}

func JediConsular() {
	ClearScreen()
	fmt.Println("                      ", Cyan, "LONG TIME AGO IN A GALAXY FAR,")
	fmt.Println("                      FAR AWAY...", Reset)
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println(Yellow, "      ▄▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀█     █▀▀▀▀▀█        █▀▀▀▀▀▀▀▀▀▄        ")
	fmt.Println("     █                            █    █   ▄   █       █   █▀▀▄   █        ")
	fmt.Println("      ▀▄    ▀█▀▀▀▀▀▀▀▀▀█   █▀▀▀▀▀▀▀   █   █ █   █      █   ▀▀▀  ▄▀         ")
	fmt.Println("        ▀▄    ▀▄       █   █         █   █▄▄▄█   █     █   ▄     ▀▄        ")
	fmt.Println(" ▄▄▄▄▄▄▄▄▄█▄    ▀▄     █   █        █    ▄▄▄▄▄    █    █   █▀▄     ▀▄▄▄▄▄▄▄▄▄▄")
	fmt.Println(" █               █     █   █       █    █     █    █   █   █  ▀▄             █")
	fmt.Println(" █▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▀     █▄▄▄█      █▄▄▄▄█       █▄▄▄▄█  █▄▄▄█    ▀▄▄▄▄▄▄▄▄▄▄▄▄█")
	fmt.Println("")
	fmt.Println("█▀▀▀▀█     █▀▀▀█     █▀▀▀▀█   █▀▀▀▀▀█        █▀▀▀▀▀▀▀▀▀▄      ▄▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀█")
	fmt.Println(" █    █   █     █   █    █   █   ▄   █       █   █▀▀▄   █    █                █")
	fmt.Println("  █    █ █       █ █    █   █   █ █   █      █   ▀▀▀  ▄▀      ▀▄    ▀█▀▀▀▀▀▀▀▀▀")
	fmt.Println("   █    ▀    ▄    ▀    █   █   █▄▄▄█   █     █   ▄     ▀▄       ▀▄    ▀▄")
	fmt.Println("    █       █ █       █   █    ▄▄▄▄▄    █    █   █▀▄     ▀▄▄▄▄▄▄▄▄█▄    ▀▄")
	fmt.Println("     █     █   █     █   █    █     █    █   █   █  ▀▄                    █")
	fmt.Println("      █▄▄▄█     █▄▄▄█   █▄▄▄▄█       █▄▄▄▄█  █▄▄▄█    ▀▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▀")
	time.Sleep(time.Second * 5)
	ClearScreen()
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("                                  PROJET RED ")
	fmt.Println("")
	fmt.Println("                                 SITH WARRIOR")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("                                  PROJET RED ")
	fmt.Println("")
	fmt.Println("                                 SITH WARRIOR")
	fmt.Println("")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("                                  PROJET RED ")
	fmt.Println("")
	fmt.Println("                                 SITH WARRIOR")
	fmt.Println("")
	fmt.Println("                           Evil threatens to consume")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("                                  PROJET RED ")
	fmt.Println("")
	fmt.Println("                                 SITH WARRIOR")
	fmt.Println("")
	fmt.Println("                           Evil threatens to consume")
	fmt.Println("                           the entire galaxy. During the ")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("                                  PROJET RED ")
	fmt.Println("")
	fmt.Println("                                 SITH WARRIOR")
	fmt.Println("")
	fmt.Println("                           Evil threatens to consume")
	fmt.Println("                           the entire galaxy. During the ")
	fmt.Println("                           last war, the implacable")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("                                  PROJET RED ")
	fmt.Println("")
	fmt.Println("                                 SITH WARRIOR")
	fmt.Println("")
	fmt.Println("                           Evil threatens to consume")
	fmt.Println("                           the entire galaxy. During the ")
	fmt.Println("                           last war, the implacable")
	fmt.Println("                           onslaught led by the Sith Empire")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("                                  PROJET RED ")
	fmt.Println("")
	fmt.Println("                                 SITH WARRIOR")
	fmt.Println("")
	fmt.Println("                           Evil threatens to consume")
	fmt.Println("                           the entire galaxy. During the")
	fmt.Println("                           last war, the implacable")
	fmt.Println("                           onslaught led by the Sith Empire")
	fmt.Println("                           destroyed the Jedi Temple and")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("                                  PROJET RED ")
	fmt.Println("")
	fmt.Println("                                 SITH WARRIOR")
	fmt.Println("")
	fmt.Println("                           Evil threatens to consume")
	fmt.Println("                           the entire galaxy. During the")
	fmt.Println("                           last war, the implacable")
	fmt.Println("                           onslaught led by the Sith Empire")
	fmt.Println("                           destroyed the Jedi Temple and")
	fmt.Println("                           drove the defenders of the ")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("                                  PROJET RED ")
	fmt.Println("")
	fmt.Println("                                 SITH WARRIOR")
	fmt.Println("")
	fmt.Println("                           Evil threatens to consume")
	fmt.Println("                           the entire galaxy. During the")
	fmt.Println("                           last war, the implacable")
	fmt.Println("                           onslaught led by the Sith Empire")
	fmt.Println("                           destroyed the Jedi Temple and")
	fmt.Println("                           drove the defenders of the ")
	fmt.Println("                           Republic into exile.")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("                                  PROJET RED ")
	fmt.Println("")
	fmt.Println("                                 SITH WARRIOR")
	fmt.Println("")
	fmt.Println("                           Evil threatens to consume")
	fmt.Println("                           the entire galaxy. During the")
	fmt.Println("                           last war, the implacable")
	fmt.Println("                           onslaught led by the Sith Empire")
	fmt.Println("                           destroyed the Jedi Temple and")
	fmt.Println("                           drove the defenders of the")
	fmt.Println("                           Republic into exile.")
	fmt.Println("")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("                                  PROJET RED ")
	fmt.Println("")
	fmt.Println("                                 SITH WARRIOR")
	fmt.Println("")
	fmt.Println("                           Evil threatens to consume")
	fmt.Println("                           the entire galaxy. During the")
	fmt.Println("                           last war, the implacable")
	fmt.Println("                           onslaught led by the Sith Empire")
	fmt.Println("                           destroyed the Jedi Temple and")
	fmt.Println("                           drove the defenders of the")
	fmt.Println("                           Republic into exile.")
	fmt.Println("")
	fmt.Println("                           A fragile peace was concluded")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("                                  PROJET RED ")
	fmt.Println("")
	fmt.Println("                                 SITH WARRIOR")
	fmt.Println("")
	fmt.Println("                           Evil threatens to consume")
	fmt.Println("                           the entire galaxy. During the")
	fmt.Println("                           last war, the implacable")
	fmt.Println("                           onslaught led by the Sith Empire")
	fmt.Println("                           destroyed the Jedi Temple and")
	fmt.Println("                           drove the defenders of the")
	fmt.Println("                           Republic into exile.")
	fmt.Println("")
	fmt.Println("                           A fragile peace was concluded")
	fmt.Println("                           and the Jedi returned to the planet")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println("")
	fmt.Println("")
	fmt.Println("                                  PROJET RED ")
	fmt.Println("")
	fmt.Println("                                 SITH WARRIOR")
	fmt.Println("")
	fmt.Println("                           Evil threatens to consume")
	fmt.Println("                           the entire galaxy. During the")
	fmt.Println("                           last war, the implacable")
	fmt.Println("                           onslaught led by the Sith Empire")
	fmt.Println("                           destroyed the Jedi Temple and")
	fmt.Println("                           drove the defenders of the")
	fmt.Println("                           Republic into exile.")
	fmt.Println("")
	fmt.Println("                           A fragile peace was concluded")
	fmt.Println("                           and the Jedi returned to the planet")
	fmt.Println("                           they had long since ")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println("")
	fmt.Println("                                  PROJET RED ")
	fmt.Println("")
	fmt.Println("                                 SITH WARRIOR")
	fmt.Println("")
	fmt.Println("                           Evil threatens to consume")
	fmt.Println("                           the entire galaxy. During the")
	fmt.Println("                           last war, the implacable")
	fmt.Println("                           onslaught led by the Sith Empire")
	fmt.Println("                           destroyed the Jedi Temple and")
	fmt.Println("                           drove the defenders of the")
	fmt.Println("                           Republic into exile.")
	fmt.Println("")
	fmt.Println("                           A fragile peace was concluded")
	fmt.Println("                           and the Jedi returned to the planet")
	fmt.Println("                           they had long since ")
	fmt.Println("                           left, TYPHON, in order to establish")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println("                                  PROJET RED ")
	fmt.Println("")
	fmt.Println("                                 SITH WARRIOR")
	fmt.Println("")
	fmt.Println("                           Evil threatens to consume")
	fmt.Println("                           the entire galaxy. During the")
	fmt.Println("                           last war, the implacable")
	fmt.Println("                           onslaught led by the Sith Empire")
	fmt.Println("                           destroyed the Jedi Temple and")
	fmt.Println("                           drove the defenders of the")
	fmt.Println("                           Republic into exile.")
	fmt.Println("")
	fmt.Println("                           A fragile peace was concluded")
	fmt.Println("                           and the Jedi returned to the planet")
	fmt.Println("                           they had long since ")
	fmt.Println("                           left, TYPHON, in order to establish")
	fmt.Println("                           regroup and investigate")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println(" ")
	fmt.Println("                                 SITH WARRIOR")
	fmt.Println("")
	fmt.Println("                           Evil threatens to consume")
	fmt.Println("                           the entire galaxy. During the")
	fmt.Println("                           last war, the implacable")
	fmt.Println("                           onslaught led by the Sith Empire")
	fmt.Println("                           destroyed the Jedi Temple and")
	fmt.Println("                           drove the defenders of the")
	fmt.Println("                           Republic into exile.")
	fmt.Println("")
	fmt.Println("                           A fragile peace was concluded")
	fmt.Println("                           and the Jedi returned to the planet")
	fmt.Println("                           they had long since ")
	fmt.Println("                           left, TYPHON, in order to establish")
	fmt.Println("                           regroup and investigate")
	fmt.Println("                           their distant origins")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println("                                 SITH WARRIOR")
	fmt.Println("")
	fmt.Println("                           Evil threatens to consume")
	fmt.Println("                           the entire galaxy. During the")
	fmt.Println("                           last war, the implacable")
	fmt.Println("                           onslaught led by the Sith Empire")
	fmt.Println("                           destroyed the Jedi Temple and")
	fmt.Println("                           drove the defenders of the")
	fmt.Println("                           Republic into exile.")
	fmt.Println("")
	fmt.Println("                           A fragile peace was concluded")
	fmt.Println("                           and the Jedi returned to the planet")
	fmt.Println("                           they had long since ")
	fmt.Println("                           left, TYPHON, in order to establish")
	fmt.Println("                           regroup and investigate")
	fmt.Println("                           their distant origins")
	fmt.Println(" ")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println("   ")
	fmt.Println("                           Evil threatens to consume")
	fmt.Println("                           the entire galaxy. During the")
	fmt.Println("                           last war, the implacable")
	fmt.Println("                           onslaught led by the Sith Empire")
	fmt.Println("                           destroyed the Jedi Temple and")
	fmt.Println("                           drove the defenders of the")
	fmt.Println("                           Republic into exile.")
	fmt.Println("")
	fmt.Println("                           A fragile peace was concluded")
	fmt.Println("                           and the Jedi returned to the planet")
	fmt.Println("                           they had long since ")
	fmt.Println("                           left, TYPHON, in order to establish")
	fmt.Println("                           regroup and investigate")
	fmt.Println("                           their distant origins")
	fmt.Println(" ")
	fmt.Println("                           Today, a wise young padawan")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println("                           Evil threatens to consume")
	fmt.Println("                           the entire galaxy. During the")
	fmt.Println("                           last war, the implacable")
	fmt.Println("                           onslaught led by the Sith Empire")
	fmt.Println("                           destroyed the Jedi Temple and")
	fmt.Println("                           drove the defenders of the")
	fmt.Println("                           Republic into exile.")
	fmt.Println("")
	fmt.Println("                           A fragile peace was concluded")
	fmt.Println("                           and the Jedi returned to the planet")
	fmt.Println("                           they had long since ")
	fmt.Println("                           left, TYPHON, in order to establish")
	fmt.Println("                           regroup and investigate")
	fmt.Println("                           their distant origins")
	fmt.Println(" ")
	fmt.Println("                           Today, a wise young padawan")
	fmt.Println("                           full of wisdom explores the ")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println("                           the entire galaxy. During the")
	fmt.Println("                           last war, the implacable")
	fmt.Println("                           onslaught led by the Sith Empire")
	fmt.Println("                           destroyed the Jedi Temple and")
	fmt.Println("                           drove the defenders of the")
	fmt.Println("                           Republic into exile.")
	fmt.Println("")
	fmt.Println("                           A fragile peace was concluded")
	fmt.Println("                           and the Jedi returned to the planet")
	fmt.Println("                           they had long since ")
	fmt.Println("                           left, TYPHON, in order to establish")
	fmt.Println("                           regroup and investigate")
	fmt.Println("                           their distant origins")
	fmt.Println(" ")
	fmt.Println("                           Today, a wise young padawan")
	fmt.Println("                           full of wisdom explores the ")
	fmt.Println("                           ruins of the mountain regions")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println("                           last war, the implacable")
	fmt.Println("                           onslaught led by the Sith Empire")
	fmt.Println("                           destroyed the Jedi Temple and")
	fmt.Println("                           drove the defenders of the")
	fmt.Println("                           Republic into exile.")
	fmt.Println("")
	fmt.Println("                           A fragile peace was concluded")
	fmt.Println("                           and the Jedi returned to the planet")
	fmt.Println("                           they had long since ")
	fmt.Println("                           left, TYPHON, in order to establish")
	fmt.Println("                           regroup and investigate")
	fmt.Println("                           their distant origins")
	fmt.Println(" ")
	fmt.Println("                           Today, a wise young padawan")
	fmt.Println("                           full of wisdom explores the ")
	fmt.Println("                           ruins of the mountain regions")
	fmt.Println("                           of Typhoon on a perilous")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println("                           onslaught led by the Sith Empire")
	fmt.Println("                           destroyed the Jedi Temple and")
	fmt.Println("                           drove the defenders of the")
	fmt.Println("                           Republic into exile.")
	fmt.Println("")
	fmt.Println("                           A fragile peace was concluded")
	fmt.Println("                           and the Jedi returned to the planet")
	fmt.Println("                           they had long since ")
	fmt.Println("                           left, TYPHON, in order to establish")
	fmt.Println("                           regroup and investigate")
	fmt.Println("                           their distant origins")
	fmt.Println(" ")
	fmt.Println("                           Today, a wise young padawan")
	fmt.Println("                           full of wisdom explores the ")
	fmt.Println("                           ruins of the mountain regions")
	fmt.Println("                           of Typhoon on a perilous")
	fmt.Println("                           quest to become a Jedi")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println("                           destroyed the Jedi Temple and")
	fmt.Println("                           drove the defenders of the")
	fmt.Println("                           Republic into exile.")
	fmt.Println("")
	fmt.Println("                           A fragile peace was concluded")
	fmt.Println("                           and the Jedi returned to the planet")
	fmt.Println("                           they had long since ")
	fmt.Println("                           left, TYPHON, in order to establish")
	fmt.Println("                           regroup and investigate")
	fmt.Println("                           their distant origins")
	fmt.Println(" ")
	fmt.Println("                           Today, a wise young padawan")
	fmt.Println("                           full of wisdom explores the ")
	fmt.Println("                           ruins of the mountain regions")
	fmt.Println("                           of Typhoon on a perilous")
	fmt.Println("                           quest to become a Jedi")
	fmt.Println("                           and unravel the mysteries ")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println("                           drove the defenders of the")
	fmt.Println("                           Republic into exile.")
	fmt.Println("")
	fmt.Println("                           A fragile peace was concluded")
	fmt.Println("                           and the Jedi returned to the planet")
	fmt.Println("                           they had long since ")
	fmt.Println("                           left, TYPHON, in order to establish")
	fmt.Println("                           regroup and investigate")
	fmt.Println("                           their distant origins")
	fmt.Println(" ")
	fmt.Println("                           Today, a wise young padawan")
	fmt.Println("                           full of wisdom explores the ")
	fmt.Println("                           ruins of the mountain regions")
	fmt.Println("                           of Typhoon on a perilous")
	fmt.Println("                           quest to become a Jedi")
	fmt.Println("                           and unravel the mysteries ")
	fmt.Println("                           of the Force...")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println("                           Republic into exile.")
	fmt.Println("")
	fmt.Println("                           A fragile peace was concluded")
	fmt.Println("                           and the Jedi returned to the planet")
	fmt.Println("                           they had long since ")
	fmt.Println("                           left, TYPHON, in order to establish")
	fmt.Println("                           regroup and investigate")
	fmt.Println("                           their distant origins")
	fmt.Println(" ")
	fmt.Println("                           Today, a wise young padawan")
	fmt.Println("                           full of wisdom explores the ")
	fmt.Println("                           ruins of the mountain regions")
	fmt.Println("                           of Typhoon on a perilous")
	fmt.Println("                           quest to become a Jedi")
	fmt.Println("                           and unravel the mysteries ")
	fmt.Println("                           of the Force...")
	fmt.Println(" ")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println("")
	fmt.Println("                           A fragile peace was concluded")
	fmt.Println("                           and the Jedi returned to the planet")
	fmt.Println("                           they had long since ")
	fmt.Println("                           left, TYPHON, in order to establish")
	fmt.Println("                           regroup and investigate")
	fmt.Println("                           their distant origins")
	fmt.Println(" ")
	fmt.Println("                           Today, a wise young padawan")
	fmt.Println("                           full of wisdom explores the ")
	fmt.Println("                           ruins of the mountain regions")
	fmt.Println("                           of Typhoon on a perilous")
	fmt.Println("                           quest to become a Jedi")
	fmt.Println("                           and unravel the mysteries ")
	fmt.Println("                           of the Force...")
	fmt.Println("")
	fmt.Println(" ")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println("                           A fragile peace was concluded")
	fmt.Println("                           and the Jedi returned to the planet")
	fmt.Println("                           they had long since ")
	fmt.Println("                           left, TYPHON, in order to establish")
	fmt.Println("                           regroup and investigate")
	fmt.Println("                           their distant origins")
	fmt.Println(" ")
	fmt.Println("                           Today, a wise young padawan")
	fmt.Println("                           full of wisdom explores the ")
	fmt.Println("                           ruins of the mountain regions")
	fmt.Println("                           of Typhoon on a perilous")
	fmt.Println("                           quest to become a Jedi")
	fmt.Println("                           and unravel the mysteries ")
	fmt.Println("                           of the Force...")
	fmt.Println("     ")
	fmt.Println("")
	fmt.Println(" ")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println("                           and the Jedi returned to the planet")
	fmt.Println("                           they had long since ")
	fmt.Println("                           left, TYPHON, in order to establish")
	fmt.Println("                           regroup and investigate")
	fmt.Println("                           their distant origins")
	fmt.Println(" ")
	fmt.Println("                           Today, a wise young padawan")
	fmt.Println("                           full of wisdom explores the ")
	fmt.Println("                           ruins of the mountain regions")
	fmt.Println("                           of Typhoon on a perilous")
	fmt.Println("                           quest to become a Jedi")
	fmt.Println("                           and unravel the mysteries ")
	fmt.Println("                           of the Force...")
	fmt.Println("  ")
	fmt.Println("     ")
	fmt.Println("")
	fmt.Println(" ")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println("                           they had long since ")
	fmt.Println("                           left, TYPHON, in order to establish")
	fmt.Println("                           regroup and investigate")
	fmt.Println("                           their distant origins")
	fmt.Println(" ")
	fmt.Println("                           Today, a wise young padawan")
	fmt.Println("                           full of wisdom explores the ")
	fmt.Println("                           ruins of the mountain regions")
	fmt.Println("                           of Typhoon on a perilous")
	fmt.Println("                           quest to become a Jedi")
	fmt.Println("                           and unravel the mysteries ")
	fmt.Println("                           of the Force...")
	fmt.Println(" ")
	fmt.Println("  ")
	fmt.Println("     ")
	fmt.Println("")
	fmt.Println(" ")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println("                           left, TYPHON, in order to establish")
	fmt.Println("                           regroup and investigate")
	fmt.Println("                           their distant origins")
	fmt.Println(" ")
	fmt.Println("                           Today, a wise young padawan")
	fmt.Println("                           full of wisdom explores the ")
	fmt.Println("                           ruins of the mountain regions")
	fmt.Println("                           of Typhoon on a perilous")
	fmt.Println("                           quest to become a Jedi")
	fmt.Println("                           and unravel the mysteries ")
	fmt.Println("                           of the Force...")
	fmt.Println(" ")
	fmt.Println(" ")
	fmt.Println("  ")
	fmt.Println("     ")
	fmt.Println("")
	fmt.Println(" ")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println("                           regroup and investigate")
	fmt.Println("                           their distant origins")
	fmt.Println(" ")
	fmt.Println("                           Today, a wise young padawan")
	fmt.Println("                           full of wisdom explores the ")
	fmt.Println("                           ruins of the mountain regions")
	fmt.Println("                           of Typhoon on a perilous")
	fmt.Println("                           quest to become a Jedi")
	fmt.Println("                           and unravel the mysteries ")
	fmt.Println("                           of the Force...")
	fmt.Println(" ")
	fmt.Println(" ")
	fmt.Println(" ")
	fmt.Println("  ")
	fmt.Println("     ")
	fmt.Println("")
	fmt.Println(" ")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println("                           their distant origins")
	fmt.Println(" ")
	fmt.Println("                           Today, a wise young padawan")
	fmt.Println("                           full of wisdom explores the ")
	fmt.Println("                           ruins of the mountain regions")
	fmt.Println("                           of Typhoon on a perilous")
	fmt.Println("                           quest to become a Jedi")
	fmt.Println("                           and unravel the mysteries ")
	fmt.Println("                           of the Force...")
	fmt.Println("  ")
	fmt.Println(" ")
	fmt.Println(" ")
	fmt.Println(" ")
	fmt.Println("  ")
	fmt.Println("     ")
	fmt.Println("")
	fmt.Println(" ")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println(" ")
	fmt.Println("                           Today, a wise young padawan")
	fmt.Println("                           full of wisdom explores the ")
	fmt.Println("                           ruins of the mountain regions")
	fmt.Println("                           of Typhoon on a perilous")
	fmt.Println("                           quest to become a Jedi")
	fmt.Println("                           and unravel the mysteries ")
	fmt.Println("                           of the Force...")
	fmt.Println(" ")
	fmt.Println("  ")
	fmt.Println(" ")
	fmt.Println(" ")
	fmt.Println(" ")
	fmt.Println("  ")
	fmt.Println("     ")
	fmt.Println("")
	fmt.Println(" ")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println("                           Today, a wise young padawan")
	fmt.Println("                           full of wisdom explores the ")
	fmt.Println("                           ruins of the mountain regions")
	fmt.Println("                           of Typhoon on a perilous")
	fmt.Println("                           quest to become a Jedi")
	fmt.Println("                           and unravel the mysteries ")
	fmt.Println("                           of the Force...")
	fmt.Println(" ")
	fmt.Println(" ")
	fmt.Println("  ")
	fmt.Println(" ")
	fmt.Println(" ")
	fmt.Println(" ")
	fmt.Println("  ")
	fmt.Println("     ")
	fmt.Println("")
	fmt.Println(" ")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println("                           full of wisdom explores the ")
	fmt.Println("                           ruins of the mountain regions")
	fmt.Println("                           of Typhoon on a perilous")
	fmt.Println("                           quest to become a Jedi")
	fmt.Println("                           and unravel the mysteries ")
	fmt.Println("                           of the Force...")
	fmt.Println("  ")
	fmt.Println(" ")
	fmt.Println(" ")
	fmt.Println("  ")
	fmt.Println(" ")
	fmt.Println(" ")
	fmt.Println(" ")
	fmt.Println("  ")
	fmt.Println("     ")
	fmt.Println("")
	fmt.Println(" ")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println("                           ruins of the mountain regions")
	fmt.Println("                           of Typhoon on a perilous")
	fmt.Println("                           quest to become a Jedi")
	fmt.Println("                           and unravel the mysteries ")
	fmt.Println("                           of the Force...")
	fmt.Println(" ")
	fmt.Println("  ")
	fmt.Println(" ")
	fmt.Println(" ")
	fmt.Println("  ")
	fmt.Println(" ")
	fmt.Println(" ")
	fmt.Println(" ")
	fmt.Println("  ")
	fmt.Println("     ")
	fmt.Println("")
	fmt.Println(" ")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println("                           of Typhoon on a perilous")
	fmt.Println("                           quest to become a Jedi")
	fmt.Println("                           and unravel the mysteries ")
	fmt.Println("                           of the Force...")
	fmt.Println("   ")
	fmt.Println(" ")
	fmt.Println("  ")
	fmt.Println(" ")
	fmt.Println(" ")
	fmt.Println("  ")
	fmt.Println(" ")
	fmt.Println(" ")
	fmt.Println(" ")
	fmt.Println("  ")
	fmt.Println("     ")
	fmt.Println("")
	fmt.Println(" ")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println("                           quest to become a Jedi")
	fmt.Println("                           and unravel the mysteries ")
	fmt.Println("                           of the Force...")
	fmt.Println("  ")
	fmt.Println("   ")
	fmt.Println(" ")
	fmt.Println("  ")
	fmt.Println(" ")
	fmt.Println(" ")
	fmt.Println("  ")
	fmt.Println(" ")
	fmt.Println(" ")
	fmt.Println(" ")
	fmt.Println("  ")
	fmt.Println("     ")
	fmt.Println("")
	fmt.Println(" ")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println("                           and unravel the mysteries ")
	fmt.Println("                           of the Force...")
	fmt.Println("  ")
	fmt.Println("  ")
	fmt.Println("   ")
	fmt.Println(" ")
	fmt.Println("  ")
	fmt.Println(" ")
	fmt.Println(" ")
	fmt.Println("  ")
	fmt.Println(" ")
	fmt.Println(" ")
	fmt.Println(" ")
	fmt.Println("  ")
	fmt.Println("     ")
	fmt.Println("")
	fmt.Println(" ")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println("                           of the Force...", Reset)
	fmt.Println(" ")
	fmt.Println("  ")
	fmt.Println("  ")
	fmt.Println("   ")
	fmt.Println(" ")
	fmt.Println("  ")
	fmt.Println(" ")
	fmt.Println(" ")
	fmt.Println("  ")
	fmt.Println(" ")
	fmt.Println(" ")
	fmt.Println(" ")
	fmt.Println("  ")
	fmt.Println("     ")
	fmt.Println("")
	fmt.Println(" ")
	time.Sleep(time.Second * 2)
	ClearScreen()
	Quete1(&save.Personnage)
}

func ClearScreen() {
	var cmd *exec.Cmd
	// Détecter le système d'exploitation
	switch runtime.GOOS {
	case "windows":
		// Commande pour Windows
		cmd = exec.Command("cmd", "/c", "cls")
	default:
		// Commande pour les systèmes Unix-like
		cmd = exec.Command("clear")
	}
	// Définir la sortie de la commande sur Stdout
	cmd.Stdout = os.Stdout
	cmd.Run()
}

func Quete1(MC *save.Perso) {
	fmt.Printf("Librarian : So you want the simulate the fight betwen you and Obi-wan Kenobi?")
	time.Sleep(1 * time.Second)
	fmt.Printf("(1)Yes     (2)I just want to tain my technic.I think he is a good test for that.")
	var choix string
	fmt.Scan(&choix)
	_, verification := strconv.Atoi(choix)
	for verification != nil {
		fmt.Println("for ", verification)
		ClearScreen()
		choix = ""
		fmt.Println("(1)Yes     (2)I just want to train my technics.I think he is a good test for that.")
		fmt.Println("\nWe ask you to enter 1 or 2")
		fmt.Scan(&choix)
		_, verification = strconv.Atoi(choix)
	}
	ClearScreen()
	fmt.Printf("Librarian : Okay, I start the simulation.")
	ClearScreen()
	Obi_Wan := save.Mob{"Obi-wan", 100, 100, 20, []save.Abilite{save.Abilite{"Light saber", 0, 10, 0, 1, 0, 0, "Light Saber of obi wan", 0, 0}}, map[save.Item]int{}, 1000}
	fight.Fight(MC, &Obi_Wan, true)
	fmt.Println("Librarian : Congratulations, you win the level 4 / 10 of this simulation.")
}

func Quete2(MC *save.Perso) {
	fmt.Printf("Librarian : So you want the simulate the fight betwen you and Yoda ?")
	time.Sleep(1 * time.Second)
	fmt.Printf("(1)Yes     (2)Yes I want to see his experiece")
	var choix string
	fmt.Scan(&choix)
	_, verification := strconv.Atoi(choix)
	for verification != nil {
		fmt.Println("for ", verification)
		ClearScreen()
		choix = ""
		fmt.Println("(1)Yes     (2)I just want to train my technics.I think he is a good test for that.")
		fmt.Println("\nWe ask you to enter 1 or 2")
		fmt.Scan(&choix)
		_, verification = strconv.Atoi(choix)
	}
	ClearScreen()
	fmt.Printf("Librarian : Okay, I start the simulation.")
	ClearScreen()
	Obi_Wan := save.Mob{"Yoda", 300, 300, 60, []save.Abilite{save.Abilite{"Light saber", 0, 10, 0, 1, 0, 0, "Light Saber of yoda", 0, 0}, save.Abilite{"Self-Healing", 0, 0, 70, 1, 0, 0, "Self healing", 0, 0}}, map[save.Item]int{}, 1000}
	fight.Fight(MC, &Obi_Wan, true)
	fmt.Println("Librarian : Congratulations, you win the level 8 / 10 of this simulation.")
}
