package guerriersith

import (
	"fmt"
	"time"
)

func Intro() {
	clearScreen()
	fmt.Println("                      ", Cyan, "LONG TIME AGO IN A GALAXY FAR,")
	fmt.Println("                      FAR AWAY...", Reset)
	time.Sleep(time.Second * 2)
	clearScreen()
	fmt.Println(Yellow, "      ▄▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀█     █▀▀▀▀▀█        █▀▀▀▀▀▀▀▀▀▄        ")
	fmt.Println("     █                            █    █   ▄   █       █   █▀▀▄   █        ")
	fmt.Println("      ▀▄    ▀█▀▀▀▀▀▀▀▀▀█   █▀▀▀▀▀▀▀   █   █ █   █      █   ▀▀▀  ▄▀         ")
	fmt.Println("        ▀▄    ▀▄       █   █         █   █▄▄▄█   █     █   ▄     ▀▄        ")
	fmt.Println(" ▄▄▄▄▄▄▄▄▄█▄    ▀▄     █   █        █    ▄▄▄▄▄    █    █   █▀▄     ▀▄▄▄▄▄▄▄▄▄▄")
	fmt.Println(" █               █     █   █       █    █     █    █   █   █  ▀▄             █")
	fmt.Println(" █▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▀     █▄▄▄█      █▄▄▄▄█       █▄▄▄▄█  █▄▄▄█    ▀▄▄▄▄▄▄▄▄▄▄▄▄█")
	fmt.Println("")
	fmt.Println("█▀▀▀▀█     █▀▀▀█     █▀▀▀▀█   █▀▀▀▀▀█        █▀▀▀▀▀▀▀▀▀▄      ▄▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀█")
	fmt.Println(" █    █   █     █   █    █   █   ▄   █       █   █▀▀▄   █    █                █")
	fmt.Println("  █    █ █       █ █    █   █   █ █   █      █   ▀▀▀  ▄▀      ▀▄    ▀█▀▀▀▀▀▀▀▀▀")
	fmt.Println("   █    ▀    ▄    ▀    █   █   █▄▄▄█   █     █   ▄     ▀▄       ▀▄    ▀▄")
	fmt.Println("    █       █ █       █   █    ▄▄▄▄▄    █    █   █▀▄     ▀▄▄▄▄▄▄▄▄█▄    ▀▄")
	fmt.Println("     █     █   █     █   █    █     █    █   █   █  ▀▄                    █")
	fmt.Println("      █▄▄▄█     █▄▄▄█   █▄▄▄▄█       █▄▄▄▄█  █▄▄▄█    ▀▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▀")
	time.Sleep(time.Second * 5)
	clearScreen()
	fmt.Println("")
	fmt.Println("")
	fmt.Println("                                  PROJET RED ")
	fmt.Println("                                 SITH WARRIOR")
	time.Sleep(time.Second * 2)
	clearScreen()
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("                                PROJET RED ")
	fmt.Println("                               SITH WARRIOR")
	fmt.Println("")
	fmt.Println("             		    The SITH EMPIRE tightens its")
	time.Sleep(time.Second * 2)
	clearScreen()
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("                                PROJET RED ")
	fmt.Println("                               SITH WARRIOR")
	fmt.Println("")
	fmt.Println("             		     The SITH EMPIRE tightens its")
	fmt.Println("                        grip  on  the  galaxy. The")
	time.Sleep(time.Second * 2)
	clearScreen()
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("                                PROJET RED ")
	fmt.Println("                               SITH WARRIOR")
	fmt.Println("")
	fmt.Println("             		     The SITH EMPIRE tightens its")
	fmt.Println("                        grip  on  the  galaxy. The")
	fmt.Println("                        Galactic Republic  and its")
	time.Sleep(time.Second * 2)
	clearScreen()
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("                                PROJET RED ")
	fmt.Println("                               SITH WARRIOR")
	fmt.Println(" ")
	fmt.Println("             		     The SITH EMPIRE tightens its")
	fmt.Println("                        grip  on  the  galaxy. The")
	fmt.Println("                        Galactic Republic  and its")
	fmt.Println("                        Jedi defenders lie weakened")
	time.Sleep(time.Second * 2)
	clearScreen()
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("                                PROJET RED ")
	fmt.Println("                               SITH WARRIOR")
	fmt.Println("")
	fmt.Println("             		     The SITH EMPIRE tightens its")
	fmt.Println("                        grip  on  the  galaxy. The")
	fmt.Println("                        Galactic Republic  and its")
	fmt.Println("                        Jedi defenders lie weakened")
	fmt.Println("                        and vulnerable after the")
	time.Sleep(time.Second * 2)
	clearScreen()
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("                                PROJET RED ")
	fmt.Println("                               SITH WARRIOR")
	fmt.Println("")
	fmt.Println("             		     The SITH EMPIRE tightens its")
	fmt.Println("                        grip  on  the  galaxy. The")
	fmt.Println("                        Galactic Republic  and its")
	fmt.Println("                        Jedi defenders lie weakened")
	fmt.Println("                        and vulnerable after the")
	fmt.Println("                        Empire's successful military")
	time.Sleep(time.Second * 2)
	clearScreen()
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("                                PROJET RED ")
	fmt.Println("                               SITH WARRIOR")
	fmt.Println("")
	fmt.Println("             		     The SITH EMPIRE tightens its")
	fmt.Println("                        grip  on  the  galaxy. The")
	fmt.Println("                        Galactic Republic  and its")
	fmt.Println("                        Jedi defenders lie weakened")
	fmt.Println("                        and vulnerable after the")
	fmt.Println("                        Empire's successful military")
	fmt.Println("                        campaign.")
	time.Sleep(time.Second * 2)
	clearScreen()
	fmt.Println("")
	fmt.Println("")
	fmt.Println("                                PROJET RED ")
	fmt.Println("                               SITH WARRIOR")
	fmt.Println("")
	fmt.Println("             		     The SITH EMPIRE tightens its")
	fmt.Println("                        grip  on  the  galaxy. The")
	fmt.Println("                        Galactic Republic  and its")
	fmt.Println("                        Jedi defenders lie weakened")
	fmt.Println("                        and vulnerable after the")
	fmt.Println("                        Empire's successful military")
	fmt.Println("                        campaign.")
	fmt.Println("")
	time.Sleep(time.Second * 2)
	clearScreen()
	fmt.Println("")
	fmt.Println("                                PROJET RED ")
	fmt.Println("                               SITH WARRIOR")
	fmt.Println("")
	fmt.Println("             		     The SITH EMPIRE tightens its")
	fmt.Println("                        grip  on  the  galaxy. The")
	fmt.Println("                        Galactic Republic  and its")
	fmt.Println("                        Jedi defenders lie weakened")
	fmt.Println("                        and vulnerable after the")
	fmt.Println("                        Empire's successful military")
	fmt.Println("                        campaign.")
	fmt.Println("")
	fmt.Println("                        With a fragile peace negotiated,")
	time.Sleep(time.Second * 2)
	clearScreen()
	fmt.Println("                                PROJET RED ")
	fmt.Println("                               SITH WARRIOR")
	fmt.Println("")
	fmt.Println("             		     The SITH EMPIRE tightens its")
	fmt.Println("                        grip  on  the  galaxy. The")
	fmt.Println("                        Galactic Republic  and its")
	fmt.Println("                        Jedi defenders lie weakened")
	fmt.Println("                        and vulnerable after the")
	fmt.Println("                        Empire's successful military")
	fmt.Println("                        campaign.")
	fmt.Println("")
	fmt.Println("                        With a fragile peace negotiated,")
	fmt.Println("                        the Empire sends all potential")
	time.Sleep(time.Second * 2)
	clearScreen()
	fmt.Println("                               SITH WARRIOR")
	fmt.Println("")
	fmt.Println("             		     The SITH EMPIRE tightens its")
	fmt.Println("                        grip  on  the  galaxy. The")
	fmt.Println("                        Galactic Republic  and its")
	fmt.Println("                        Jedi defenders lie weakened")
	fmt.Println("                        and vulnerable after the")
	fmt.Println("                        Empire's successful military")
	fmt.Println("                        campaign.")
	fmt.Println("")
	fmt.Println("                        With a fragile peace negotiated,")
	fmt.Println("                        the Empire sends all potential")
	fmt.Println("                        Sith  to  undergo  cruel  and")
	time.Sleep(time.Second * 2)
	clearScreen()
	fmt.Println("")
	fmt.Println("             		     The SITH EMPIRE tightens its")
	fmt.Println("                        grip  on  the  galaxy. The")
	fmt.Println("                        Galactic Republic  and its")
	fmt.Println("                        Jedi defenders lie weakened")
	fmt.Println("                        and vulnerable after the")
	fmt.Println("                        Empire's successful military")
	fmt.Println("                        campaign.")
	fmt.Println("")
	fmt.Println("                        With a fragile peace negotiated,")
	fmt.Println("                        the Empire sends all potential")
	fmt.Println("                        Sith  to  undergo  cruel  and")
	fmt.Println("                        deadly trials at its Academy on")
	time.Sleep(time.Second * 2)
	clearScreen()
	fmt.Println("             		     The SITH EMPIRE tightens its")
	fmt.Println("                        grip  on  the  galaxy. The")
	fmt.Println("                        Galactic Republic  and its")
	fmt.Println("                        Jedi defenders lie weakened")
	fmt.Println("                        and vulnerable after the")
	fmt.Println("                        Empire's successful military")
	fmt.Println("                        campaign.")
	fmt.Println("")
	fmt.Println("                        With a fragile peace negotiated,")
	fmt.Println("                        the Empire sends all potential")
	fmt.Println("                        Sith  to  undergo  cruel  and")
	fmt.Println("                        deadly trials at its Academy on")
	fmt.Println("                        the harsh planet KORRIBAN.")
	time.Sleep(time.Second * 2)
	clearScreen()
	fmt.Println("                        grip  on  the  galaxy. The")
	fmt.Println("                        Galactic Republic  and its")
	fmt.Println("                        Jedi defenders lie weakened")
	fmt.Println("                        and vulnerable after the")
	fmt.Println("                        Empire's successful military")
	fmt.Println("                        campaign.")
	fmt.Println("")
	fmt.Println("                        With a fragile peace negotiated,")
	fmt.Println("                        the Empire sends all potential")
	fmt.Println("                        Sith  to  undergo  cruel  and")
	fmt.Println("                        deadly trials at its Academy on")
	fmt.Println("                        the harsh planet KORRIBAN.")
	fmt.Println("")
	time.Sleep(time.Second * 2)
	clearScreen()
	fmt.Println("                        Galactic Republic  and its")
	fmt.Println("                        Jedi defenders lie weakened")
	fmt.Println("                        and vulnerable after the")
	fmt.Println("                        Empire's successful military")
	fmt.Println("                        campaign.")
	fmt.Println("")
	fmt.Println("                        With a fragile peace negotiated,")
	fmt.Println("                        the Empire sends all potential")
	fmt.Println("                        Sith  to  undergo  cruel  and")
	fmt.Println("                        deadly trials at its Academy on")
	fmt.Println("                        the harsh planet KORRIBAN.")
	fmt.Println("")
	fmt.Println("                        Today,  one  of  the Empire's")
	time.Sleep(time.Second * 2)
	clearScreen()
	fmt.Println("                        Jedi defenders lie weakened")
	fmt.Println("                        and vulnerable after the")
	fmt.Println("                        Empire's successful military")
	fmt.Println("                        campaign.")
	fmt.Println("")
	fmt.Println("                        With a fragile peace negotiated,")
	fmt.Println("                        the Empire sends all potential")
	fmt.Println("                        Sith  to  undergo  cruel  and")
	fmt.Println("                        deadly trials at its Academy on")
	fmt.Println("                        the harsh planet KORRIBAN.")
	fmt.Println("")
	fmt.Println("                        Today,  one  of  the Empire's")
	fmt.Println("                        most promising young warriors")
	time.Sleep(time.Second * 2)
	clearScreen()
	fmt.Println("                        and vulnerable after the")
	fmt.Println("                        Empire's successful military")
	fmt.Println("                        campaign.")
	fmt.Println("")
	fmt.Println("                        With a fragile peace negotiated,")
	fmt.Println("                        the Empire sends all potential")
	fmt.Println("                        Sith  to  undergo  cruel  and")
	fmt.Println("                        deadly trials at its Academy on")
	fmt.Println("                        the harsh planet KORRIBAN.")
	fmt.Println("")
	fmt.Println("                        Today,  one  of  the Empire's")
	fmt.Println("                        most promising young warriors")
	fmt.Println("                        has  been  secretly  summoned")
	time.Sleep(time.Second * 2)
	clearScreen()
	fmt.Println("                        Empire's successful military")
	fmt.Println("                        campaign.")
	fmt.Println("")
	fmt.Println("                        With a fragile peace negotiated,")
	fmt.Println("                        the Empire sends all potential")
	fmt.Println("                        Sith  to  undergo  cruel  and")
	fmt.Println("                        deadly trials at its Academy on")
	fmt.Println("                        the harsh planet KORRIBAN.")
	fmt.Println("")
	fmt.Println("                        Today,  one  of  the Empire's")
	fmt.Println("                        most promising young warriors")
	fmt.Println("                        has  been  secretly  summoned")
	fmt.Println("                        by an influential overseer to")
	time.Sleep(time.Second * 2)
	clearScreen()
	fmt.Println("                        campaign.")
	fmt.Println("")
	fmt.Println("                        With a fragile peace negotiated,")
	fmt.Println("                        the Empire sends all potential")
	fmt.Println("                        Sith  to  undergo  cruel  and")
	fmt.Println("                        deadly trials at its Academy on")
	fmt.Println("                        the harsh planet KORRIBAN.")
	fmt.Println("")
	fmt.Println("                        Today,  one  of  the Empire's")
	fmt.Println("                        most promising young warriors")
	fmt.Println("                        has  been  secretly  summoned")
	fmt.Println("                        by an influential overseer to")
	fmt.Println("                        face the dark side trials much")
	time.Sleep(time.Second * 2)
	clearScreen()
	fmt.Println("")
	fmt.Println("                        With a fragile peace negotiated,")
	fmt.Println("                        the Empire sends all potential")
	fmt.Println("                        Sith  to  undergo  cruel  and")
	fmt.Println("                        deadly trials at its Academy on")
	fmt.Println("                        the harsh planet KORRIBAN.")
	fmt.Println("")
	fmt.Println("                        Today,  one  of  the Empire's")
	fmt.Println("                        most promising young warriors")
	fmt.Println("                        has  been  secretly  summoned")
	fmt.Println("                        by an influential overseer to")
	fmt.Println("                        face the dark side trials much")
	fmt.Println("                        sooner than expected....")
	time.Sleep(time.Second * 2)
	clearScreen()
	fmt.Println("                        the Empire sends all potential")
	fmt.Println("                        Sith  to  undergo  cruel  and")
	fmt.Println("                        deadly trials at its Academy on")
	fmt.Println("                        the harsh planet KORRIBAN.")
	fmt.Println("")
	fmt.Println("                        Today,  one  of  the Empire's")
	fmt.Println("                        most promising young warriors")
	fmt.Println("                        has  been  secretly  summoned")
	fmt.Println("                        by an influential overseer to")
	fmt.Println("                        face the dark side trials much")
	fmt.Println("                        sooner than expected....")
	time.Sleep(time.Second * 2)
	clearScreen()
	fmt.Println("                        Sith  to  undergo  cruel  and")
	fmt.Println("                        deadly trials at its Academy on")
	fmt.Println("                        the harsh planet KORRIBAN.")
	fmt.Println("")
	fmt.Println("                        Today,  one  of  the Empire's")
	fmt.Println("                        most promising young warriors")
	fmt.Println("                        has  been  secretly  summoned")
	fmt.Println("                        by an influential overseer to")
	fmt.Println("                        face the dark side trials much")
	fmt.Println("                        sooner than expected....")
	time.Sleep(time.Second * 2)
	clearScreen()
	fmt.Println("                        deadly trials at its Academy on")
	fmt.Println("                        the harsh planet KORRIBAN.")
	fmt.Println("")
	fmt.Println("                        Today,  one  of  the Empire's")
	fmt.Println("                        most promising young warriors")
	fmt.Println("                        has  been  secretly  summoned")
	fmt.Println("                        by an influential overseer to")
	fmt.Println("                        face the dark side trials much")
	fmt.Println("                        sooner than expected....")
	time.Sleep(time.Second * 2)
	clearScreen()
	fmt.Println("                        the harsh planet KORRIBAN.")
	fmt.Println("")
	fmt.Println("                        Today,  one  of  the Empire's")
	fmt.Println("                        most promising young warriors")
	fmt.Println("                        has  been  secretly  summoned")
	fmt.Println("                        by an influential overseer to")
	fmt.Println("                        face the dark side trials much")
	fmt.Println("                        sooner than expected....")
	time.Sleep(time.Second * 2)
	clearScreen()
	fmt.Println("")
	fmt.Println("                        Today,  one  of  the Empire's")
	fmt.Println("                        most promising young warriors")
	fmt.Println("                        has  been  secretly  summoned")
	fmt.Println("                        by an influential overseer to")
	fmt.Println("                        face the dark side trials much")
	fmt.Println("                        sooner than expected....")
	time.Sleep(time.Second * 2)
	clearScreen()
	fmt.Println("                        Today,  one  of  the Empire's")
	fmt.Println("                        most promising young warriors")
	fmt.Println("                        has  been  secretly  summoned")
	fmt.Println("                        by an influential overseer to")
	fmt.Println("                        face the dark side trials much")
	fmt.Println("                        sooner than expected....")
	time.Sleep(time.Second * 2)
	clearScreen()
	fmt.Println("                        most promising young warriors")
	fmt.Println("                        has  been  secretly  summoned")
	fmt.Println("                        by an influential overseer to")
	fmt.Println("                        face the dark side trials much")
	fmt.Println("                        sooner than expected....")
	time.Sleep(time.Second * 2)
	clearScreen()
	fmt.Println("                        has  been  secretly  summoned")
	fmt.Println("                        by an influential overseer to")
	fmt.Println("                        face the dark side trials much")
	fmt.Println("                        sooner than expected....")
	time.Sleep(time.Second * 2)
	clearScreen()
	fmt.Println("                        by an influential overseer to")
	fmt.Println("                        face the dark side trials much")
	fmt.Println("                        sooner than expected....")
	time.Sleep(time.Second * 2)
	clearScreen()
	fmt.Println("                        face the dark side trials much")
	fmt.Println("                        sooner than expected....")
	time.Sleep(time.Second * 2)
	clearScreen()
	fmt.Println("                        sooner than expected....", Reset)
	time.Sleep(time.Second * 2)
	clearScreen()
}