package jeux

import (
	"fmt"
	"os"
	"os/exec"
	"runtime"
	"strconv"
	"time"
)

const (
	Reset   = "\033[0m"
	Red     = "\033[91m"
	Green   = "\033[32m"
	Yellow  = "\033[93m"
	Violet  = "\033[95m"
	Cyan    = "\033[96m"
	White   = "\033[37m"
	gray    = "\033[90m"
)

// Les differentes classes pour le jedi
var classeJedi1 Classe = Classe{"Way of the spirit", 100, []Abilite{Abilite{"Meditation", 10, 0, 30, 1, 0, 0, "An Abilite for rest a litle bit during a ", 0, 0}, Abilite{"Force Attack", 15, 20, 0, 1, 0, 0, "A Force Attack who project the ennemie on the wall", 0, 0}}, 100}
var classeJedi2 Classe = Classe{"Way of the training", 150, []Abilite{Abilite{"Hissatsu Majishirīzu", 20, 30, 0, 1, 0, 0, "A serie of punch", 0, 0}, Abilite{"right hook", 40, 40, 0, 1, 0, 0, "A right hook on the face of the ennemie", 0, 0}}, 150}
var classeJedi3 Classe = Classe{"Way of the instinct", 120, []Abilite{Abilite{"Charge of the Jedi", 20, 35, 0, 1, 0, 0, "Charge on the enemie", 0, 0}, Abilite{"Dot of the jedi", 40, 10, 0, 1, 0, 0, "A dot build in Jedi laboratory", 3, 10}}, 120}

var ClasseJediList [3]Classe = [3]Classe{classeJedi1, classeJedi2, classeJedi3}

func JediKnight() {
	ClearScreen()
	fmt.Println("                      ", Cyan, "LONG TIME AGO IN A GALAXY FAR,")
	fmt.Println("                      FAR AWAY...", Reset)
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println(Yellow, "      ▄▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀█     █▀▀▀▀▀█        █▀▀▀▀▀▀▀▀▀▄        ")
	fmt.Println("     █                            █    █   ▄   █       █   █▀▀▄   █        ")
	fmt.Println("      ▀▄    ▀█▀▀▀▀▀▀▀▀▀█   █▀▀▀▀▀▀▀   █   █ █   █      █   ▀▀▀  ▄▀         ")
	fmt.Println("        ▀▄    ▀▄       █   █         █   █▄▄▄█   █     █   ▄     ▀▄        ")
	fmt.Println(" ▄▄▄▄▄▄▄▄▄█▄    ▀▄     █   █        █    ▄▄▄▄▄    █    █   █▀▄     ▀▄▄▄▄▄▄▄▄▄▄")
	fmt.Println(" █               █     █   █       █    █     █    █   █   █  ▀▄             █")
	fmt.Println(" █▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▀     █▄▄▄█      █▄▄▄▄█       █▄▄▄▄█  █▄▄▄█    ▀▄▄▄▄▄▄▄▄▄▄▄▄█")
	fmt.Println("")
	fmt.Println("█▀▀▀▀█     █▀▀▀█     █▀▀▀▀█   █▀▀▀▀▀█        █▀▀▀▀▀▀▀▀▀▄      ▄▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀█")
	fmt.Println(" █    █   █     █   █    █   █   ▄   █       █   █▀▀▄   █    █                █")
	fmt.Println("  █    █ █       █ █    █   █   █ █   █      █   ▀▀▀  ▄▀      ▀▄    ▀█▀▀▀▀▀▀▀▀▀")
	fmt.Println("   █    ▀    ▄    ▀    █   █   █▄▄▄█   █     █   ▄     ▀▄       ▀▄    ▀▄")
	fmt.Println("    █       █ █       █   █    ▄▄▄▄▄    █    █   █▀▄     ▀▄▄▄▄▄▄▄▄█▄    ▀▄")
	fmt.Println("     █     █   █     █   █    █     █    █   █   █  ▀▄                    █")
	fmt.Println("      █▄▄▄█     █▄▄▄█   █▄▄▄▄█       █▄▄▄▄█  █▄▄▄█    ▀▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▀")
	time.Sleep(time.Second * 5)
	ClearScreen()
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("                                  PROJET RED ")
	fmt.Println("")
	fmt.Println("                                 SITH WARRIOR")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("                                  PROJET RED ")
	fmt.Println("")
	fmt.Println("                                 SITH WARRIOR")
	fmt.Println("")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("                                  PROJET RED ")
	fmt.Println("")
	fmt.Println("                                 SITH WARRIOR")
	fmt.Println("")
	fmt.Println("                           It is a dark era for the")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("                                  PROJET RED ")
	fmt.Println("")
	fmt.Println("                                 SITH WARRIOR")
	fmt.Println("")
	fmt.Println("                           It is a dark  era  for  the")
	fmt.Println("                           JEDI ORDER. The Sith Empire")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("                                  PROJET RED ")
	fmt.Println("")
	fmt.Println("                                 SITH WARRIOR")
	fmt.Println("")
	fmt.Println("                           It is a dark  era  for  the")
	fmt.Println("                           JEDI ORDER. The Sith Empire")
	fmt.Println("                           obliterared the Jedi Temple")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("                                  PROJET RED ")
	fmt.Println("")
	fmt.Println("                                 SITH WARRIOR")
	fmt.Println("")
	fmt.Println("                           It is a dark  era  for  the")
	fmt.Println("                           JEDI ORDER. The Sith Empire")
	fmt.Println("                           obliterared the Jedi Temple")
	fmt.Println("                           on Coruscant and slaughtered")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("                                  PROJET RED ")
	fmt.Println("")
	fmt.Println("                                 SITH WARRIOR")
	fmt.Println("")
	fmt.Println("                           It is a dark  era  for  the")
	fmt.Println("                           JEDI ORDER. The Sith Empire")
	fmt.Println("                           obliterared the Jedi Temple")
	fmt.Println("                           on Coruscant and slaughtered")
	fmt.Println("                           many of the Republic's brave")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("                                  PROJET RED ")
	fmt.Println("")
	fmt.Println("                                 SITH WARRIOR")
	fmt.Println("")
	fmt.Println("                          It is a dark era for the")
	fmt.Println("                          JEDI ORDER. The Sith Empire")
	fmt.Println("                          obliterared the Jedi Temple")
	fmt.Println("                          on Coruscant and slaughtered")
	fmt.Println("                          many of the Republic's brave")
	fmt.Println("                          defenders during the last war.")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("                                  PROJET RED ")
	fmt.Println("")
	fmt.Println("                                 SITH WARRIOR")
	fmt.Println("")
	fmt.Println("                          It is a dark era for the")
	fmt.Println("                          JEDI ORDER. The Sith Empire")
	fmt.Println("                          obliterared the Jedi Temple")
	fmt.Println("                          on Coruscant and slaughtered")
	fmt.Println("                          many of the Republic's brave")
	fmt.Println("                          defenders during the last war.")
	fmt.Println("")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("                                  PROJET RED ")
	fmt.Println("")
	fmt.Println("                                 SITH WARRIOR")
	fmt.Println("")
	fmt.Println("                          It is a dark era for the")
	fmt.Println("                          JEDI ORDER. The Sith Empire")
	fmt.Println("                          obliterared the Jedi Temple")
	fmt.Println("                          on Coruscant and slaughtered")
	fmt.Println("                          many of the Republic's brave")
	fmt.Println("                          defenders during the last war.")
	fmt.Println("")
	fmt.Println("                          The surviving Jedi have")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("                                  PROJET RED ")
	fmt.Println("")
	fmt.Println("                                 SITH WARRIOR")
	fmt.Println("")
	fmt.Println("                          It is a dark era for the")
	fmt.Println("                          JEDI ORDER. The Sith Empire")
	fmt.Println("                          obliterared the Jedi Temple")
	fmt.Println("                          on Coruscant and slaughtered")
	fmt.Println("                          many of the Republic's brave")
	fmt.Println("                          defenders during the last war.")
	fmt.Println("")
	fmt.Println("                          The surviving Jedi have")
	fmt.Println("                          withdrawn to their ancient")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println("")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("                                  PROJET RED ")
	fmt.Println("")
	fmt.Println("                                 SITH WARRIOR")
	fmt.Println("")
	fmt.Println("                          It is a dark era for the")
	fmt.Println("                          JEDI ORDER. The Sith Empire")
	fmt.Println("                          obliterared the Jedi Temple")
	fmt.Println("                          on Coruscant and slaughtered")
	fmt.Println("                          many of the Republic's brave")
	fmt.Println("                          defenders during the last war.")
	fmt.Println("")
	fmt.Println("                          The surviving Jedi have")
	fmt.Println("                          withdrawn to their ancient")
	fmt.Println("                          homeworld of TYTHON, where")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println("")
	fmt.Println("")
	fmt.Println("                                  PROJET RED ")
	fmt.Println("")
	fmt.Println("                                 SITH WARRIOR")
	fmt.Println("")
	fmt.Println("                          It is a dark era for the")
	fmt.Println("                          JEDI ORDER. The Sith Empire")
	fmt.Println("                          obliterared the Jedi Temple")
	fmt.Println("                          on Coruscant and slaughtered")
	fmt.Println("                          many of the Republic's brave")
	fmt.Println("                          defenders during the last war.")
	fmt.Println("")
	fmt.Println("                          The surviving Jedi have")
	fmt.Println("                          withdrawn to their ancient")
	fmt.Println("                          homeworld of TYTHON, where")
	fmt.Println("                          they take advantage of a")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println("")
	fmt.Println("                                  PROJET RED ")
	fmt.Println("")
	fmt.Println("                                 SITH WARRIOR")
	fmt.Println("")
	fmt.Println("                          It is a dark era for the")
	fmt.Println("                          JEDI ORDER. The Sith Empire")
	fmt.Println("                          obliterared the Jedi Temple")
	fmt.Println("                          on Coruscant and slaughtered")
	fmt.Println("                          many of the Republic's brave")
	fmt.Println("                          defenders during the last war.")
	fmt.Println("")
	fmt.Println("                          The surviving Jedi have")
	fmt.Println("                          withdrawn to their ancient")
	fmt.Println("                          homeworld of TYTHON, where")
	fmt.Println("                          they take advantage of a")
	fmt.Println("                          fragile peace to train a new")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println("                                  PROJET RED ")
	fmt.Println("")
	fmt.Println("                                 SITH WARRIOR")
	fmt.Println("")
	fmt.Println("                          It is a dark era for the")
	fmt.Println("                          JEDI ORDER. The Sith Empire")
	fmt.Println("                          obliterared the Jedi Temple")
	fmt.Println("                          on Coruscant and slaughtered")
	fmt.Println("                          many of the Republic's brave")
	fmt.Println("                          defenders during the last war.")
	fmt.Println("")
	fmt.Println("                          The surviving Jedi have")
	fmt.Println("                          withdrawn to their ancient")
	fmt.Println("                          homeworld of TYTHON, where")
	fmt.Println("                          they take advantage of a")
	fmt.Println("                          fragile peace to train a new")
	fmt.Println("                          generation of gardians for the")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println(" ")
	fmt.Println("                                 SITH WARRIOR")
	fmt.Println("")
	fmt.Println("                          It is a dark era for the")
	fmt.Println("                          JEDI ORDER. The Sith Empire")
	fmt.Println("                          obliterared the Jedi Temple")
	fmt.Println("                          on Coruscant and slaughtered")
	fmt.Println("                          many of the Republic's brave")
	fmt.Println("                          defenders during the last war.")
	fmt.Println("")
	fmt.Println("                          The surviving Jedi have")
	fmt.Println("                          withdrawn to their ancient")
	fmt.Println("                          homeworld of TYTHON, where")
	fmt.Println("                          they take advantage of a")
	fmt.Println("                          fragile peace to train a new")
	fmt.Println("                          generation of gardians for the")
	fmt.Println("                          galaxy.")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println("                                 SITH WARRIOR")
	fmt.Println("")
	fmt.Println("                          It is a dark era for the")
	fmt.Println("                          JEDI ORDER. The Sith Empire")
	fmt.Println("                          obliterared the Jedi Temple")
	fmt.Println("                          on Coruscant and slaughtered")
	fmt.Println("                          many of the Republic's brave")
	fmt.Println("                          defenders during the last war.")
	fmt.Println("")
	fmt.Println("                          The surviving Jedi have")
	fmt.Println("                          withdrawn to their ancient")
	fmt.Println("                          homeworld of TYTHON, where")
	fmt.Println("                          they take advantage of a")
	fmt.Println("                          fragile peace to train a new")
	fmt.Println("                          generation of gardians for the")
	fmt.Println("                          galaxy.")
	fmt.Println(" ")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println("   ")
	fmt.Println("                          It is a dark era for the")
	fmt.Println("                          JEDI ORDER. The Sith Empire")
	fmt.Println("                          obliterared the Jedi Temple")
	fmt.Println("                          on Coruscant and slaughtered")
	fmt.Println("                          many of the Republic's brave")
	fmt.Println("                          defenders during the last war.")
	fmt.Println("")
	fmt.Println("                          The surviving Jedi have")
	fmt.Println("                          withdrawn to their ancient")
	fmt.Println("                          homeworld of TYTHON, where")
	fmt.Println("                          they take advantage of a")
	fmt.Println("                          fragile peace to train a new")
	fmt.Println("                          generation of gardians for the")
	fmt.Println("                          galaxy.")
	fmt.Println(" ")
	fmt.Println("                          Now a new hope emerges. A")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println("                          It is a dark era for the")
	fmt.Println("                          JEDI ORDER. The Sith Empire")
	fmt.Println("                          obliterared the Jedi Temple")
	fmt.Println("                          on Coruscant and slaughtered")
	fmt.Println("                          many of the Republic's brave")
	fmt.Println("                          defenders during the last war.")
	fmt.Println("")
	fmt.Println("                          The surviving Jedi have")
	fmt.Println("                          withdrawn to their ancient")
	fmt.Println("                          homeworld of TYTHON, where")
	fmt.Println("                          they take advantage of a")
	fmt.Println("                          fragile peace to train a new")
	fmt.Println("                          generation of gardians for the")
	fmt.Println("                          galaxy.")
	fmt.Println(" ")
	fmt.Println("                          Now a new hope emerges. A")
	fmt.Println("                          young Padawan strong in")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println("                          JEDI ORDER. The Sith Empire")
	fmt.Println("                          obliterared the Jedi Temple")
	fmt.Println("                          on Coruscant and slaughtered")
	fmt.Println("                          many of the Republic's brave")
	fmt.Println("                          defenders during the last war.")
	fmt.Println("")
	fmt.Println("                          The surviving Jedi have")
	fmt.Println("                          withdrawn to their ancient")
	fmt.Println("                          homeworld of TYTHON, where")
	fmt.Println("                          they take advantage of a")
	fmt.Println("                          fragile peace to train a new")
	fmt.Println("                          generation of gardians for the")
	fmt.Println("                          galaxy.")
	fmt.Println(" ")
	fmt.Println("                          Now a new hope emerges. A")
	fmt.Println("                          young Padawan strong in")
	fmt.Println("                          the Force journeys to Tython's")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println("                          obliterared the Jedi Temple")
	fmt.Println("                          on Coruscant and slaughtered")
	fmt.Println("                          many of the Republic's brave")
	fmt.Println("                          defenders during the last war.")
	fmt.Println("")
	fmt.Println("                          The surviving Jedi have")
	fmt.Println("                          withdrawn to their ancient")
	fmt.Println("                          homeworld of TYTHON, where")
	fmt.Println("                          they take advantage of a")
	fmt.Println("                          fragile peace to train a new")
	fmt.Println("                          generation of gardians for the")
	fmt.Println("                          galaxy.")
	fmt.Println(" ")
	fmt.Println("                          Now a new hope emerges. A")
	fmt.Println("                          young Padawan strong in")
	fmt.Println("                          the Force journeys to Tython's")
	fmt.Println("                          dangerous wilderness to")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println("                          on Coruscant and slaughtered")
	fmt.Println("                          many of the Republic's brave")
	fmt.Println("                          defenders during the last war.")
	fmt.Println("")
	fmt.Println("                          The surviving Jedi have")
	fmt.Println("                          withdrawn to their ancient")
	fmt.Println("                          homeworld of TYTHON, where")
	fmt.Println("                          they take advantage of a")
	fmt.Println("                          fragile peace to train a new")
	fmt.Println("                          generation of gardians for the")
	fmt.Println("                          galaxy.")
	fmt.Println(" ")
	fmt.Println("                          Now a new hope emerges. A")
	fmt.Println("                          young Padawan strong in")
	fmt.Println("                          the Force journeys to Tython's")
	fmt.Println("                          dangerous wilderness to")
	fmt.Println("                          complete the final Jedi trials")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println("                          many of the Republic's brave")
	fmt.Println("                          defenders during the last war.")
	fmt.Println("")
	fmt.Println("                          The surviving Jedi have")
	fmt.Println("                          withdrawn to their ancient")
	fmt.Println("                          homeworld of TYTHON, where")
	fmt.Println("                          they take advantage of a")
	fmt.Println("                          fragile peace to train a new")
	fmt.Println("                          generation of gardians for the")
	fmt.Println("                          galaxy.")
	fmt.Println(" ")
	fmt.Println("                          Now a new hope emerges. A")
	fmt.Println("                          young Padawan strong in")
	fmt.Println("                          the Force journeys to Tython's")
	fmt.Println("                          dangerous wilderness to")
	fmt.Println("                          complete the final Jedi trials")
	fmt.Println("                          and become a Knight of the")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println("                          defenders during the last war.")
	fmt.Println("")
	fmt.Println("                          The surviving Jedi have")
	fmt.Println("                          withdrawn to their ancient")
	fmt.Println("                          homeworld of TYTHON, where")
	fmt.Println("                          they take advantage of a")
	fmt.Println("                          fragile peace to train a new")
	fmt.Println("                          generation of gardians for the")
	fmt.Println("                          galaxy.")
	fmt.Println(" ")
	fmt.Println("                          Now a new hope emerges. A")
	fmt.Println("                          young Padawan strong in")
	fmt.Println("                          the Force journeys to Tython's")
	fmt.Println("                          dangerous wilderness to")
	fmt.Println("                          complete the final Jedi trials")
	fmt.Println("                          and become a Knight of the")
	fmt.Println("                          Republic....")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println("")
	fmt.Println("                          The surviving Jedi have")
	fmt.Println("                          withdrawn to their ancient")
	fmt.Println("                          homeworld of TYTHON, where")
	fmt.Println("                          they take advantage of a")
	fmt.Println("                          fragile peace to train a new")
	fmt.Println("                          generation of gardians for the")
	fmt.Println("                          galaxy.")
	fmt.Println(" ")
	fmt.Println("                          Now a new hope emerges. A")
	fmt.Println("                          young Padawan strong in")
	fmt.Println("                          the Force journeys to Tython's")
	fmt.Println("                          dangerous wilderness to")
	fmt.Println("                          complete the final Jedi trials")
	fmt.Println("                          and become a Knight of the")
	fmt.Println("                          Republic....")
	fmt.Println(" ")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println("                          The surviving Jedi have")
	fmt.Println("                          withdrawn to their ancient")
	fmt.Println("                          homeworld of TYTHON, where")
	fmt.Println("                          they take advantage of a")
	fmt.Println("                          fragile peace to train a new")
	fmt.Println("                          generation of gardians for the")
	fmt.Println("                          galaxy.")
	fmt.Println(" ")
	fmt.Println("                          Now a new hope emerges. A")
	fmt.Println("                          young Padawan strong in")
	fmt.Println("                          the Force journeys to Tython's")
	fmt.Println("                          dangerous wilderness to")
	fmt.Println("                          complete the final Jedi trials")
	fmt.Println("                          and become a Knight of the")
	fmt.Println("                          Republic....")
	fmt.Println("")
	fmt.Println(" ")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println("                          withdrawn to their ancient")
	fmt.Println("                          homeworld of TYTHON, where")
	fmt.Println("                          they take advantage of a")
	fmt.Println("                          fragile peace to train a new")
	fmt.Println("                          generation of gardians for the")
	fmt.Println("                          galaxy.")
	fmt.Println(" ")
	fmt.Println("                          Now a new hope emerges. A")
	fmt.Println("                          young Padawan strong in")
	fmt.Println("                          the Force journeys to Tython's")
	fmt.Println("                          dangerous wilderness to")
	fmt.Println("                          complete the final Jedi trials")
	fmt.Println("                          and become a Knight of the")
	fmt.Println("                          Republic....")
	fmt.Println("     ")
	fmt.Println("")
	fmt.Println(" ")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println("                          homeworld of TYTHON, where")
	fmt.Println("                          they take advantage of a")
	fmt.Println("                          fragile peace to train a new")
	fmt.Println("                          generation of gardians for the")
	fmt.Println("                          galaxy.")
	fmt.Println(" ")
	fmt.Println("                          Now a new hope emerges. A")
	fmt.Println("                          young Padawan strong in")
	fmt.Println("                          the Force journeys to Tython's")
	fmt.Println("                          dangerous wilderness to")
	fmt.Println("                          complete the final Jedi trials")
	fmt.Println("                          and become a Knight of the")
	fmt.Println("                          Republic....")
	fmt.Println("  ")
	fmt.Println("     ")
	fmt.Println("")
	fmt.Println(" ")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println("                          they take advantage of a")
	fmt.Println("                          fragile peace to train a new")
	fmt.Println("                          generation of gardians for the")
	fmt.Println("                          galaxy.")
	fmt.Println(" ")
	fmt.Println("                          Now a new hope emerges. A")
	fmt.Println("                          young Padawan strong in")
	fmt.Println("                          the Force journeys to Tython's")
	fmt.Println("                          dangerous wilderness to")
	fmt.Println("                          complete the final Jedi trials")
	fmt.Println("                          and become a Knight of the")
	fmt.Println("                          Republic....")
	fmt.Println(" ")
	fmt.Println("  ")
	fmt.Println("     ")
	fmt.Println("")
	fmt.Println(" ")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println("                          fragile peace to train a new")
	fmt.Println("                          generation of gardians for the")
	fmt.Println("                          galaxy.")
	fmt.Println(" ")
	fmt.Println("                          Now a new hope emerges. A")
	fmt.Println("                          young Padawan strong in")
	fmt.Println("                          the Force journeys to Tython's")
	fmt.Println("                          dangerous wilderness to")
	fmt.Println("                          complete the final Jedi trials")
	fmt.Println("                          and become a Knight of the")
	fmt.Println("                          Republic....")
	fmt.Println(" ")
	fmt.Println(" ")
	fmt.Println("  ")
	fmt.Println("     ")
	fmt.Println("")
	fmt.Println(" ")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println("                          generation of gardians for the")
	fmt.Println("                          galaxy.")
	fmt.Println(" ")
	fmt.Println("                          Now a new hope emerges. A")
	fmt.Println("                          young Padawan strong in")
	fmt.Println("                          the Force journeys to Tython's")
	fmt.Println("                          dangerous wilderness to")
	fmt.Println("                          complete the final Jedi trials")
	fmt.Println("                          and become a Knight of the")
	fmt.Println("                          Republic....")
	fmt.Println(" ")
	fmt.Println(" ")
	fmt.Println(" ")
	fmt.Println("  ")
	fmt.Println("     ")
	fmt.Println("")
	fmt.Println(" ")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println("                          galaxy.")
	fmt.Println(" ")
	fmt.Println("                          Now a new hope emerges. A")
	fmt.Println("                          young Padawan strong in")
	fmt.Println("                          the Force journeys to Tython's")
	fmt.Println("                          dangerous wilderness to")
	fmt.Println("                          complete the final Jedi trials")
	fmt.Println("                          and become a Knight of the")
	fmt.Println("                          Republic....")
	fmt.Println("  ")
	fmt.Println(" ")
	fmt.Println(" ")
	fmt.Println(" ")
	fmt.Println("  ")
	fmt.Println("     ")
	fmt.Println("")
	fmt.Println(" ")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println(" ")
	fmt.Println("                          Now a new hope emerges. A")
	fmt.Println("                          young Padawan strong in")
	fmt.Println("                          the Force journeys to Tython's")
	fmt.Println("                          dangerous wilderness to")
	fmt.Println("                          complete the final Jedi trials")
	fmt.Println("                          and become a Knight of the")
	fmt.Println("                          Republic....")
	fmt.Println(" ")
	fmt.Println("  ")
	fmt.Println(" ")
	fmt.Println(" ")
	fmt.Println(" ")
	fmt.Println("  ")
	fmt.Println("     ")
	fmt.Println("")
	fmt.Println(" ")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println("                          Now a new hope emerges. A")
	fmt.Println("                          young Padawan strong in")
	fmt.Println("                          the Force journeys to Tython's")
	fmt.Println("                          dangerous wilderness to")
	fmt.Println("                          complete the final Jedi trials")
	fmt.Println("                          and become a Knight of the")
	fmt.Println("                          Republic....")
	fmt.Println(" ")
	fmt.Println(" ")
	fmt.Println("  ")
	fmt.Println(" ")
	fmt.Println(" ")
	fmt.Println(" ")
	fmt.Println("  ")
	fmt.Println("     ")
	fmt.Println("")
	fmt.Println(" ")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println("                          young Padawan strong in")
	fmt.Println("                          the Force journeys to Tython's")
	fmt.Println("                          dangerous wilderness to")
	fmt.Println("                          complete the final Jedi trials")
	fmt.Println("                          and become a Knight of the")
	fmt.Println("                          Republic....")
	fmt.Println("  ")
	fmt.Println(" ")
	fmt.Println(" ")
	fmt.Println("  ")
	fmt.Println(" ")
	fmt.Println(" ")
	fmt.Println(" ")
	fmt.Println("  ")
	fmt.Println("     ")
	fmt.Println("")
	fmt.Println(" ")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println("                          the Force journeys to Tython's")
	fmt.Println("                          dangerous wilderness to")
	fmt.Println("                          complete the final Jedi trials")
	fmt.Println("                          and become a Knight of the")
	fmt.Println("                          Republic....")
	fmt.Println(" ")
	fmt.Println("  ")
	fmt.Println(" ")
	fmt.Println(" ")
	fmt.Println("  ")
	fmt.Println(" ")
	fmt.Println(" ")
	fmt.Println(" ")
	fmt.Println("  ")
	fmt.Println("     ")
	fmt.Println("")
	fmt.Println(" ")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println("                          dangerous wilderness to")
	fmt.Println("                          complete the final Jedi trials")
	fmt.Println("                          and become a Knight of the")
	fmt.Println("                          Republic....")
	fmt.Println("   ")
	fmt.Println(" ")
	fmt.Println("  ")
	fmt.Println(" ")
	fmt.Println(" ")
	fmt.Println("  ")
	fmt.Println(" ")
	fmt.Println(" ")
	fmt.Println(" ")
	fmt.Println("  ")
	fmt.Println("     ")
	fmt.Println("")
	fmt.Println(" ")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println("                          complete the final Jedi trials")
	fmt.Println("                          and become a Knight of the")
	fmt.Println("                          Republic....")
	fmt.Println("  ")
	fmt.Println("   ")
	fmt.Println(" ")
	fmt.Println("  ")
	fmt.Println(" ")
	fmt.Println(" ")
	fmt.Println("  ")
	fmt.Println(" ")
	fmt.Println(" ")
	fmt.Println(" ")
	fmt.Println("  ")
	fmt.Println("     ")
	fmt.Println("")
	fmt.Println(" ")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println("                          and become a Knight of the")
	fmt.Println("                          Republic....")
	fmt.Println("  ")
	fmt.Println("  ")
	fmt.Println("   ")
	fmt.Println(" ")
	fmt.Println("  ")
	fmt.Println(" ")
	fmt.Println(" ")
	fmt.Println("  ")
	fmt.Println(" ")
	fmt.Println(" ")
	fmt.Println(" ")
	fmt.Println("  ")
	fmt.Println("     ")
	fmt.Println("")
	fmt.Println(" ")
	time.Sleep(time.Second * 2)
	ClearScreen()
	fmt.Println("                          Republic....", Reset)
	fmt.Println(" ")
	fmt.Println("  ")
	fmt.Println("  ")
	fmt.Println("   ")
	fmt.Println(" ")
	fmt.Println("  ")
	fmt.Println(" ")
	fmt.Println(" ")
	fmt.Println("  ")
	fmt.Println(" ")
	fmt.Println(" ")
	fmt.Println(" ")
	fmt.Println("  ")
	fmt.Println("     ")
	fmt.Println("")
	fmt.Println(" ")
	time.Sleep(time.Second * 2)
	ClearScreen()
	Quete1(&Personnage)
}

func ClearScreen() {
	var cmd *exec.Cmd
	// Détecter le système d'exploitation
	switch runtime.GOOS {
	case "windows":
		// Commande pour Windows
		cmd = exec.Command("cmd", "/c", "cls")
	default:
		// Commande pour les systèmes Unix-like
		cmd = exec.Command("clear")
	}
	// Définir la sortie de la commande sur Stdout
	cmd.Stdout = os.Stdout
	cmd.Run()
}

func CampaingJediKnight(MC *Perso) {
	Quete1(MC)
}

func Quete1(MC *Perso) {
	//Prologue
	ClearScreen()
	fmt.Println("Clone : Are you okay general?")
	time.Sleep(3 * time.Second)
	fmt.Println("\nYou : Yes, I fell asleep a bit")
	time.Sleep(3 * time.Second)
	fmt.Println("\nClone : Need I remind you of the current mission?")
	time.Sleep(3 * time.Second)
	fmt.Println("\nYou : Yes please")
	time.Sleep(3 * time.Second)
	fmt.Println("\n Clone : Okay")
	ClearScreen()
	time.Sleep(3 * time.Second)
	fmt.Println("Clone : We are on Coruscant, on the floor minus 32.")
	time.Sleep(3 * time.Second)
	ClearScreen()
	fmt.Println("Clone : Our mission is to bring criminals who are in relation with the head of black march.")
	time.Sleep(3 * time.Second)
	ClearScreen()
	fmt.Println("Clone : WARNING")
	time.Sleep(3 * time.Second)
	ClearScreen()
	fmt.Println("Unknown : You are lucky " + MC.Name + ".")
	time.Sleep(2 * time.Second)
	fmt.Println("\nYou : Oh, you think, so we will see.")
	time.Sleep(4 * time.Second)
	ClearScreen()
	fmt.Println("You decide to fight this unknown enemy.")
	//unknown := Mob{"Brigand", 100, 100, 0, []Abilite{Abilite{"punch", 0, 10, 0, 0, 0, 0, "Just a punch"}}, map[Item]int{}, 100}
	//Fight(MC, &unknown, true)
	//fin du premier combat imperdable pour le joueur
	ClearScreen()
	fmt.Println("Brigands : I didn't expect a jedi, I must contact the chef.")
	time.Sleep(3 * time.Second)
	ClearScreen()
	fmt.Println("Clone : do we follow him ?")
	time.Sleep(1 * time.Second)
	fmt.Println("\n(1) Yes, but beware of the trap			(2) Yes, hurry up")
	fmt.Println("\nEnter 1 or 2")
	var choix string
	fmt.Scan(&choix)
	_, verification := strconv.Atoi(choix)
	for verification != nil {
		fmt.Println("for ", verification)
		ClearScreen()
		choix = ""
		fmt.Println("(1) Yes, but beware of the trap			(2) Yes, hurry up")
		fmt.Println("\nWe ask you to enter 1 or 2")
		fmt.Scan(&choix)
		_, verification = strconv.Atoi(choix)
	}
	ClearScreen()
	fmt.Println("Clone : Ok")
	time.Sleep(3 * time.Second)
	ClearScreen()
	fmt.Println("You follow the Brigand")
	time.Sleep(2 * time.Second)
	ClearScreen()
	fmt.Println("you enter an abandoned building")
	time.Sleep(3 * time.Second)
	ClearScreen()
	fmt.Println("Unknown : Hi jedi")
	time.Sleep(2 * time.Second)
	ClearScreen()
	fmt.Println("The chief of the brignands takes you aside and decide to fight you")
	time.Sleep(3 * time.Second)
	ClearScreen()
	BrignandsChief := Mob{"Brignands's chief", 200, 200, 10, []Abilite{Abilite{"punch", 0, 10, 0, 0, 0, 0, "Just a punch", 0, 0}, Abilite{"Blaster", 0, 20, 0, 0, 0, 0, "A classic Blaster", 0, 0}}, map[Item]int{}, 0}
	if !Fight(MC, &BrignandsChief, true) {
		ClearScreen()
		fmt.Println("Do you want to restart Yes(1) or No(2) ?")
		fmt.Scan(&choix)
		answer, verification := strconv.Atoi(choix)
		for verification != nil && !(answer == 1 || answer == 2) {
			ClearScreen()
			choix = ""
			fmt.Println("Do you want to restart Yes(1) or No(2) ?")
			fmt.Println("\nWe ask you to enter 1 or 2")
			fmt.Scan(&choix)
			answer, verification = strconv.Atoi(choix)
		}
		if answer == 1 {
			MC.PV_actuelle = (MC.PV_max * 4) / 3
			Quete1(MC)
		} else {
			return
		}
	}
	ClearScreen()
	fmt.Println("Clone : Congratulations")
	time.Sleep(3 * time.Second)
}

func Quete2(MC *Perso) {
	//quete ou on doit escorter un senateur
	fmt.Printf("Sheev Palpatine : Hi %s, I'll send you to escort the senator Bail Organa to an appointment.\n\n", MC.Name)
	time.Sleep(2 * time.Second)
	fmt.Printf("You : Okay, okay, I'll take care of it.")
	time.Sleep(2 * time.Second)
	ClearScreen()
	fmt.Printf("Guard : Hello %s, nice to meet you.\n\n", MC.Name)
	time.Sleep(2 * time.Second)
	fmt.Printf("You : Me too, so, what is the risk of the mission ?\n\n")
	time.Sleep(2 * time.Second)
	fmt.Printf("Guard : We think a bounty hunter was hired to eliminate the senator.\n\n")
	time.Sleep(2 * time.Second)
	fmt.Printf("You : Okay, so let's go.")
	ClearScreen()
	fmt.Printf("You walk next to Bail Organa when you listen an explosion")
	time.Sleep(2 * time.Second)
	ClearScreen()
	fmt.Printf("You : Caution!")
	time.Sleep(2 * time.Second)
	ClearScreen()
	fmt.Printf("You keep the senator out of danger")
	time.Sleep(2 * time.Second)
	ClearScreen()
	fmt.Printf("You go on the sniper")
	time.Sleep(2 * time.Second)
	ClearScreen()
	fmt.Printf("You : In the name of the republic, stop.\n\n")
	time.Sleep(2 * time.Second)
	fmt.Printf("Bounty hunter : Certainly not.")
	ClearScreen()
	BountyHunter := Mob{"Bounty hunter", 300, 300, 20, []Abilite{Abilite{"Grenade", 0, 30, 0, 1, 0, 0, "A grenade who explose.", 2, 5}, Abilite{"Self-Healing", 0, 0, 20, 1, 0, 0, "Self heal", 0, 0}, Abilite{"Sniper shot", 0, 30, 0, 1, 0, 0, "Sniper shot abilite", 0, 0}}, map[Item]int{}, 500}
	if !Fight(MC, &BountyHunter, true) {
		MC.PV_actuelle = MC.PV_actuelle * 3 / 4
		Quete2(MC)
	}
	ClearScreen()
	fmt.Printf("Congratulation")
}

func End(MC *Perso) {
	fmt.Println("Dooku : Welcomme young Jedi")
	time.Sleep(2 * time.Second)
	fmt.Printf("\nYou : Hello traitor")
	time.Sleep(2 * time.Second)
	fmt.Printf("\n\nDooku : I'm not a traitor like tou say, I have just see than the Jedi High Council is corupted by the Galactic Senate.")
	time.Sleep(2 * time.Second)
	fmt.Printf("\n\nYou : You are a liar.")
	Dooku1 := Mob{"Dooku", 500, 500, 90, []Abilite{Abilite{"lightning", 0, 150, 0, 1, 0, 0, "Lightning of the dark Side", 0, 0}, Abilite{"Lighsaber", 0, 210, 0, 1, 0, 0, "Lighsaber technique", 0, 0}}, map[Item]int{}, 1000}
	res := Fight(MC, &Dooku1, true)
	if !res {
		ClearScreen()
		var choix string
		fmt.Println("Do you want to restart Yes(1) or No(2) ?")
		fmt.Scan(&choix)
		answer, verification := strconv.Atoi(choix)
		for verification != nil && !(answer == 1 || answer == 2) {
			ClearScreen()
			choix = ""
			fmt.Println("Do you want to restart Yes(1) or No(2) ?")
			fmt.Println("\nWe ask you to enter 1 or 2")
			fmt.Scan(&choix)
			answer, verification = strconv.Atoi(choix)
		}
		if answer == 1 {
			MC.PV_actuelle = (MC.PV_max * 4) / 3
			Quete1(MC)
		} else {
			return
		}
	}
	ClearScreen()
	fmt.Printf("Dooku : Not bad")
	time.Sleep(1 * time.Second)
	ClearScreen()
	fmt.Printf("Dooku : But you must do better if you want ot win")
	time.Sleep(2 * time.Second)
	Dooku2 := Mob{"Dooku", 600, 500, 70, []Abilite{Abilite{"lightning", 0, 150, 0, 1, 0, 0, "Lightning of the dark Side", 2, 15}, Abilite{"Lighsaber", 0, 210, 0, 1, 0, 0, "Lighsaber technique", 0, 0}, Abilite{"Self-Healing", 0, 0, 70, 1, 0, 0, "Self heal", 0, 0}}, map[Item]int{}, 1000}
	res = Fight(MC, &Dooku2, false)
	if !res {
		ClearScreen()
		var choix string
		fmt.Println("Do you want to restart Yes(1) or No(2) ?")
		fmt.Scan(&choix)
		answer, verification := strconv.Atoi(choix)
		for verification != nil && !(answer == 1 || answer == 2) {
			ClearScreen()
			choix = ""
			fmt.Println("Do you want to restart Yes(1) or No(2) ?")
			fmt.Println("\nWe ask you to enter 1 or 2")
			fmt.Scan(&choix)
			answer, verification = strconv.Atoi(choix)
		}
		if answer == 1 {
			MC.PV_actuelle = (MC.PV_max * 4) / 3
			Quete1(MC)
		} else {
			return
		}
	}
	fmt.Printf("Congratulations")
}
